// module.exports = {
//   production: [
//     'EmailCampaign',
//     'EmailTemplate',
//     'Filter',
//     'Order',
//     'Contract',
//     'Message',
//     'Group',
//     'Route',
//     'Note',
//     'User',
//     'Timeclock',
//     'FormDefinition',
//     'Aggregate',
//     'ReportTemplate',
//     'Task',
//     'Appointment',
//     'Timeoff',
//     'Permissions',
//     'Product',
//     'TaskTemplate'
//   ],
//   // 'Goal',
//   // 'Payroll',
//   marketing: [
//     'Email',
//     'Residence',
//     'Interest',
//     'Lead',
//     'Label',
//     'PreviousOrder'
//   ]
//   // 'PhoneCall',
//   // 'UserInteraction',
// }
/**
  "RecordRequestDefinition",
  "Email",
  "EmailCampaign",
  "Lead",
  "Order",
  "Product",
  "Interest",
  "Residence",
  "User",
  "Contract",
  "Message",
  "Note",
  "Route",
  "Group",
  "Timeclock",
  "Task",
  "Timeoff",
  "Layout",
  "EmailTemplate",
  "Appointment",
  "Aggregate",
  "Filter",
  "ReportTemplate",
  "Label",
  "PreviousOrder",
  "ScoreCard",
  "Score",
  "IDReferenceObject",
  "ContractTemplate",
  "TaskTemplate",
  "Area",
  "Job",
  "JobTemplate",
  "Payment",
  "PhoneNumber",
  "Location"
 */

module.exports = {
	production: [
		'User',
		'Residence',
		'Twillio',
		'Phonecall',
		'PaidTimeOff',
		'Note',
		'Message',
		'Scorecard',
		'Lead',
		'Timeclock',
		'UserLocation',
		'Invoice',
		'Corporation',
		'Role',
		'Payment',
		'Appointment',
		'Contract',
		'Product',
		'Permission'
	]
};
